create table images
(
    id     integer generated by default as identity
        constraint images_pkey
            primary key,
    width  integer not null,
    height integer not null,
    link   text    not null
);

alter table images
    owner to postgres;


