package infrastructure

import (
	_ "database/sql"
	"github.com/jmoiron/sqlx"
	_ "github.com/lib/pq"
	"projectServis/interfaces"
	"projectServis/user_cases"
)

const schema = `CREATE TABLE if not exists images (
Id     integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
Widht  integer
Height integer
Link   text NOT NULL,
UNIQUE(image)
)`

const makeunique = `ALTER TABLE images
ADD CONSTRAINT image UNIQUE (image);`

type DbimageConnect struct {
	dbimage *sqlx.DB
}

func NewDbimageConnect(dbimage *sqlx.DB) *DbimageConnect {
	return &DbimageConnect{dbimage: dbimage}
}

func (r DbimageConnect) MakeUniqueImageQuery() error {
	_, err := r.dbimage.Exec(makeunique)
	return err
}

func (r DbimageConnect) HistoryAll() ([]interfaces.Image, error) {
	var images []interfaces.Image

	err := r.dbimage.Select(&images, "select * from images")

	usercaseImages := make([]interfaces.Image, 0, len(images))
	for i := range images {
		usercaseImages = append(usercaseImages, interfaces.Image{Link: images[i].Link})
	}
	return usercaseImages, err
}

func (r DbimageConnect) FindImageId(id int) interfaces.Image {
	temp := interfaces.Image{}
	return temp
}

func (r DbimageConnect) ChangeImageId(id int) {
}

func (r DbimageConnect) SaveImage(image user_cases.ImageDb) (user_cases.ImageDb, error) {

	//запись данных обычная
	//_, err := r.dbimage.Exec("INSERT INTO images (width, height, link) VALUES ($1, $2, $3)",
	//	image.Width, image.Height, image.Link)

	//запись данных с получение Id
	var id int
	err := r.dbimage.QueryRow("INSERT INTO images (width, height, link) VALUES ($1, $2, $3) returning id",
		image.Width, image.Height, image.Link).Scan(&id)
	image.Id = id

	return image, err
}
